accounts/urls.py
from django.urls import path
from .import views

app_name  = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('<str:username>/profile/',views.profile,name='profile'),
    path('<str:username>/follows/',views.follows,name='follows'),



]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),
    path('', views.main, name='main'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'


urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create,name='create'),
    path('<int:id>/likes/', views.likes,name='likes'),
    path('<int:id>/likes-async/',views.likes_async, name='likes-async'),
    path('<int:id>/detail/',views.detail,name='detail'),
    path('<int:id>/delete/',views.delete,name='delete'),
    path('<int:post_id>/comments/create/',views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:id>/delete/',views.comment_delete,name='comment_delete'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField
# Create your models here.


class User(AbstractUser):
    profile_image = ResizedImageField(
        size = [300,300],
        crop = ('middle','center'),
        upload_to = 'profile',
    )


    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    # user_set(followers) =  
    # symmetrical=False => 1번에서 2번가는 것과 2번에서 1번가는 것이 다르다는 것을 알려줌 

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.

class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[400,300],
        crop=['middle','center'],
        upload_to = 'image/%Y/%m',

    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User


class CustomUserCreationform(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username','profile_image', )
                                                                
                            
class CustomAuthenticationForm(AuthenticationForm):
    pass

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user','like_users',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import CustomUserCreationform, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationform(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('posts:index')

    else:
        form = CustomUserCreationform()


    context = {
        'form': form,
    }

    return render(request,'accounts_form.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')

    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts_form.html',context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

def profile(request,username):
    user_info = User.objects.get(username=username)

    context = {
        'user_info': user_info,
    }
    return render(request,'profile.html', context)
    
def follows(request, username):
    me = request.user
    you = User.objects.get(username=username)

    # 이미 팔로잉 되어있는 경우
    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)

    return redirect('accounts:profile', username=username)

insta/views.py
from django.shortcuts import redirect

def main(request): 
    return redirect('posts:index')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required 
# Create your views here.

def index(request):
    posts = Post.objects.all().order_by('-id')

    context = {
        'posts': posts,
    }

    return render(request,'index.html',context)


def create(request):
    if request.method == 'POST':
        # 사진은 FILES 요청에 있다
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form': form,
    }

    return render(request,'form.html',context)

@login_required
def likes(request, id):
    user = request.user
    post = Post.objects.get(id=id)


    # 이미 좋아요 버튼을 누른 경우
    # if post in user.like_posts.all():
    if user in post.like_users.all():
        post.like_users.remove(user)
    # 좋아요 버튼을 아직 안누른경우
    else:
        post.like_users.add(user)



    # user.like_posts.add(post) 위와 같은 값의 코드


    return redirect('posts:index')

from django.http import JsonResponse

def likes_async(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False

    else: 
        post.like_users.add(user)
        status = True


    context = {
        'status': status,
        'count': len(post.like_users.all())
    }

    return JsonResponse(context)

def detail(request,id):

    post = Post.objects.get(id=id)
    form = CommentForm()

    context = {
        'post': post,
        'form': form,
    }

    return render(request,'detail.html',context)

@login_required
def delete(request,id):
    post = Post.objects.get(id=id)

    if request.user == post.user:
        post.delete()

    return redirect('posts:index')

@login_required
def comment_create(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        
        if form.is_valid():
            comment = form.save(commit=False)

            # comment.article = article
            # comment.user = request.user

            comment.user_id = request.user.id
            comment.post_id = post_id

            comment.save()

            return redirect('posts:detail',id=post_id)
    else:
        form = CommentForm()

    context = {
        'form': form,
    }

    return redirect('posts:detail', id=post_id)

@login_required
def comment_delete(request, post_id, id):
    comment = Comment.objects.get(id=id)    
    if request.user == comment.user:
        comment.delete()

    return redirect('posts:detail', id=post_id)

accounts/templates/accounts_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body %}
<form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
</form>


{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}



{% block body %}
    <div class="row">
        <div class="col-4">
            {% if user_info.profile_image %}
                <img src="{{ user_info.profile_image.url }}" alt="" class="rounded-circle img-fluid">
            {% else %}
                <img src="/media/profile/default.jpg" alt="" class="rounded-circle img-fluid">
            {% endif %}
        </div>
        <div class="col-8">
            <div class="row">
                <div class="col-3">
                    {{ user_info }}
                </div>

                {% if user != user_info %}
                <div class="col-4">
                    {% if user in user_info.followers.all %}
                    <a href="{% url 'accounts:follows' username=user_info %}" class="btn btn-primary">팔로우 취소</a>
                    {% else %}
                    <a href="{% url 'accounts:follows' username=user_info %}" class="btn btn-light">팔로우</a>
                    {% endif %}
                </div>
                {% endif %}

            </div>
            <div class="row">
                <div class="col">게시물 {{user_info.post_set.all|length}}</div>
                <div class="col">팔로워 {{user_info.followers.all|length}}</div>
                <div class="col">팔로우 {{user_info.followings.all|length}}</div>
            </div>
        </div>
    </div>
    
    <div class="row row-cols-3">
        {% for post in user_info.post_set.all %}
            <div class="col">
                <div class="card">
                    <img src="{{ post.image.url }}" alt="">
                </div>
            </div>
        {% endfor %}

    </div>


{% endblock %}

posts/templates/_card.html
<div class="card my-3 mr-3 ml-3 col-12 col-md-6">
    <div class="card-header">
        {% if post.user.profile_image %} 
            <img src="{{ post.user.profile_image.url }}" alt="" class="rounded-circle" width="30px">
        {% else %}
            <img src="/media/profile/default.jpg" alt="" class="rounded-circle" width="30px">
        {% endif %}    
        <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">
            {{ post.user }}
        </a>
    </div>
    <a href="{% url 'posts:detail' id=post.id %}">
        <img src="{{ post.image.url }}" alt="">
    </a>
    <div class="card-body">
            {% if user in post.like_users.all %}
                <i class="bi bi-heart-fill heart" style="color:red" data-post-id="{{post.id}}">{{ post.like_users.all|length }}</i>
            {% else %}
                <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{ post.like_users.all|length }}</i>
            {% endif %}
            명이 좋아합니다.
        <p class="card-text"><b>{{ post.user }}</b> {{ post.content }}</p>
        
        {% if user == post.user %}
            <a href="{% url 'posts:delete' id=post.id %}">delete</a>
        {% endif %}

    </div>
</div>

posts/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="row mt-5 ">
    <div class="col-6">
        <img src="{{post.image.url}}" alt="">
    </div>
    <div class="col-6"> 
        <p>
            <b>{{post.user}}</b>
            {{post.content}}
        </p>
    </div>
</div>

<div class="row mt-3">
    {% if user.is_authenticated %}
        <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary">
        </form>
    {% endif %}
</div>

<hr>
    {% for comment in post.comment_set.all %}
        <div class="alert alert-light">
            {{comment.user}} : {{comment.content}}
            {% if user == comment.user %}
            <a class="btn btn-danger btn-sm" href="{% url 'posts:comment_delete' post_id=post.id id=comment.id %}">delete</a>
            {% endif %}
        </div>
       
        <br>
    {% endfor %}

{% endblock %}

posts/templates/form.html
{% extends 'base.html' %} 
{% load bootstrap5 %}



{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form form %}

        <input type="submit">


    </form>


{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}



{% block body %}
    <div class="row">
        {% for post in posts %}
            {% include '_card.html' %}
        {% endfor %}
    </div>


    <script>
        let likeButtons = document.querySelectorAll("i.heart") 
        // console.log(likeButtons)

        likeButtons.forEach((likeButton)=>{
            // console.log(likeButtons)
            likeButton.addEventListener("click",(event)=> {
                // console.log(event.target)

                let postId = event.target.dataset.postId
                
                likeRequest(event.target, postId)
            })
        })

        let likeRequest = async (button, postId) => {
            // console.log(button, postId)
            let likeURL = `/posts/${postId}/likes-async/`
            // console.log(likeURL)
            let response = await fetch(likeURL)
            let result = await response.json()

            // console.log(result)

            // 좋아요가 눌린경우
            if (result.status) {
                button.classList.remove('bi-heart')
                button.classList.add('bi-heart-fill')
                button.style.color = 'red'
                button.innerHTML = result.count
            // 좋아요가 취소된경우
            } else {
                button.classList.remove('bi-heart-fill')
                button.classList.add('bi-heart')
                button.style.color = 'black'
                button.innerHTML = result.count
            }

        }


    </script>

{% endblock %}

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <i class="bi bi-instagram"></i> Instagram</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'posts:create' %}">Create</a>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
            <a class="nav-link active text-primary"  aria-disabled="true" href="{% url 'accounts:profile' username=user %}">{{ user}}</a>
        </li>
            
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>

        {% endif %}

        </ul>
      </div>
    </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    {% include '_nav.html' %}
    <div class="container">
        {% block body %}
        {% endblock %}

    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>